### ISSUE TITLE
Materials and methods used in training the models

### ISSUE THREAD

**Issue by wjalal** [hamiltonoh/OrganAge#5]
Dear authors,

Thank you for your work on organ aging and for making this repository publicly available. I can see that you have included .pkl dumps of your trained models, and included the training weights in the supplements of your publication on Nature, and I understand that the training data is not included due to privacy concerns. 

However, our team from the Department of Computer Science and Engineering at Bangladesh University of Engineering and Technology would like to explore further on alternative methods to train on the dataset. We want to reproduce your outputs, and apply alternate  regressions, or explore the possibility of using neural networks here. We would be very grateful if you could make the code for training the models available to us or to the public.

**Comment by hamiltonoh** [comment]
done
