### ISSUE TITLE
Construction of the _agegap_zscore_scaler.pkl and _age_prediction_lowess.dill files

### ISSUE THREAD

**Issue by ALSKJFOI** [hamiltonoh/OrganAge#6]
Dear authors,
    Thank you for your work on organ aging and for making this repository publicly available.
    However, because our protein and your protein type are quite different, we need to retrain the model. I saw in your Organ aging model training.ipynb file how to train the model, However, there are two files _agegap_zscore_scaler.pkl and _age_prediction_lowess.dill whose generation mode is not found, so I wonder if you can provide this part of the code at your convenience, I would appreciate it.

**Comment by hamiltonoh** [comment]
updated model training and testing code in docs/
