### ISSUE TITLE
Questions for ML models and sample data

### ISSUE THREAD

**Issue by ggg5438** [hamiltonoh/OrganAge#7]
Hello,
Thank you for your great and excellent work!

I have two questions for your data:

1. In the test folder, you uploaded "df_prot.csv". Is this a part of the original KADRC data or synthesized one?
2. Are the models in the 'data/ml_models/KADRC' trained by full and original KADRC data, or the dataframe you uploaded ('test/df_prot.csv')

Again, thank you for your work!

**Comment by hamiltonoh** [comment]
Hi, thanks for your interest! The data in the test folder are sample synthesized datasets. The models are trained on the original Knight-ADRC data, which can be accessed by formal data request to the Knight-ADRC (https://www.niagads.org/knight-adrc-collection) led by Carlos Cruchaga.

**Comment by ggg5438** [comment]
Thanks!
